---
#
# Copyright 2020
# description: this playbook is dedicated for Telkomsel Indonesia
#
- hosts: all
  ignore_unreachable: yes
  any_errors_fatal: false
  become: yes
  gather_facts: true
  vars:
    all_results: {}

  tasks:
    - name: Get start time
      block:
        - setup:
            filter: ansible_date_time
          register: result
        - set_fact:
            start_time: "{{ lookup('pipe','date \"+%T %Z %F\"') }}"
      delegate_to: localhost
      become: no
      tags: always
      
    - set_fact:
        ign_var: "{{ group_names | to_nice_yaml | replace(' ','') | replace('-','')|replace('\n','') }}"
      become: no
      delegate_to: localhost
      tags: always
    - set_fact:
        rpt_path_v4: "/var/report/v4/custom-soc/{{ ign_var }}"
      become: no
      delegate_to: localhost
      tags: always
    - name: To create directory on Tower controller node for reports
      file:
        path: "{{ item }}"
        recurse: yes
        state: directory
        mode: '0777'
      with_items:
        - "{{ rpt_path_v4 }}"
      delegate_to: localhost
      become: no
      tags: always 
      ignore_errors: true

    - name: Execute CIS benchmark Scan for RHEL
      include_role:
        name: rhel7scanning
      tags: always

    - name: Get end time
      block:
        - setup:
            filter: ansible_date_time
          register: result
        - set_fact:
            end_time: "{{ lookup('pipe','date \"+%T %Z %F\"') }}"
      delegate_to: localhost
      become: no
      tags: always

    - debug:
        var: all_results

    - name: MySQL DB Security Dashboard
      import_tasks: dash-dbquery-scan-job.yml
      tags: always

    - name: Generate report
      block:
        - read_csv:
            path: files/rhel7-cis-benchmarks.csv
            fieldnames: rule,name,s_lv,ws_lv
            key: rule
          register: rules
          no_log: true
          delegate_to: localhost
          become: no
        - template:
            src: rhel7-cis-report.html.j2
            dest: /var/report/v4/custom-soc/{{ ign_var }}/{{ ansible_hostname }}.html
          delegate_to: localhost
          become: no
      tags: always
