---
# handlers file for rhel7hardening
- name: restart auditd
  command: /sbin/service auditd restart
  changed_when: no
  check_mode: no
  failed_when: no
  ignore_errors: True
  args:
    warn: no

- name: grub2cfg
  command: /sbin/grub2-mkconfig -o /boot/grub2/grub.cfg
  ignore_errors: True

- name: restart sshd
  service:
    name: sshd
    state: restarted 
  ignore_errors: True

- name: save iptables
  command: /sbin/service iptables save
  changed_when: no
  check_mode: no
  failed_when: no
  ignore_errors: True
  args:
    warn: no

- name: restart iptables
  service:
      name: iptables
      state: restarted
  ignore_errors: True