#! /bin/bash

awk -F: '($7 != "/sbin/nologin" && $7 != "/bin/false" && $1 !~ /^(root|halt|sync|shutdown)$/ ) { print $1 " " $6 }' /etc/passwd | while read user dir; do
 if [ ! -d "$dir" ] ; then
   echo "The home directory ($dir) of user $user does not exist."
 else
   if [ ! -h "$dir/.forward" -a -f "$dir/.forward" ] ; then
     echo ".forward file $dir/.forward exists"
   fi
 fi
done
